from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.units import inch

def generate_research_pdf(output_path):
    doc = SimpleDocTemplate(output_path, pagesize=letter,
                            rightMargin=72, leftMargin=72,
                            topMargin=72, bottomMargin=18)
    
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name='Justify', alignment=4))
    
    # Custom Styles
    title_style = styles['Heading1']
    title_style.alignment = 1 # Center
    title_style.textColor = colors.HexColor('#1976d2') 
    
    h2_style = styles['Heading2']
    h2_style.textColor = colors.HexColor('#333333')
    
    body_style = styles['BodyText']
    body_style.spaceAfter = 12
    
    Story = []
    
    # Title
    Story.append(Paragraph("AI-Powered gRNA Designer: System Architecture and Scoring Methodology", title_style))
    Story.append(Spacer(1, 0.2 * inch))
    
    # Author / Date
    Story.append(Paragraph("<i>Generated by gRNA Predictor Reporting Module</i>", styles['Normal']))
    Story.append(Spacer(1, 0.5 * inch))
    
    # Section 1: Introduction
    Story.append(Paragraph("1. Introduction", h2_style))
    intro_text = """
    CRISPR-Cas9 has revolutionized genomic engineering by enabling targeted modifications of DNA. 
    The efficiency of this system heavily relies on the design of the single guide RNA (sgRNA). 
    The AI-Powered gRNA Designer is a web-based tool developed to assist researchers in identifying 
    the most active and specific sgRNAs for any given target sequence. By leveraging established 
    rule-based heuristics and predictive algorithms, the tool rapidly profiles DNA segments, 
    extracts valid protospacer adjacent motifs (PAMs), and scores potential target sites.
    """
    Story.append(Paragraph(intro_text, body_style))
    
    # Section 2: Sequence Processing Pipeline
    Story.append(Paragraph("2. Sequence Processing and PAM Identification", h2_style))
    pipeline_text = """
    The backend engine is constructed using FastAPI to handle high-throughput sequence requests. 
    When a raw nucleotide sequence is submitted, the system performs the following parsing protocol:
    <br/><br/>
    <b>1. Normalization:</b> The input string is stripped of whitespace and converted to uppercase. Non-nucleotide characters are flagged as errors.<br/>
    <b>2. PAM Scanning:</b> For the standard <i>Streptococcus pyogenes</i> Cas9 (SpCas9), the system utilizes a sliding window approach to identify the 'NGG' protospacer adjacent motif.<br/>
    <b>3. Target Extraction:</b> Upon locating a valid PAM, the preceding 20-nucleotide sequence is extracted as the putative guide RNA. If the PAM is located at the 5' end of the sequence with insufficient preceding bases, it is discarded to ensure a complete 20bp guide.
    """
    Story.append(Paragraph(pipeline_text, body_style))
    
    # Section 3: Predictive Scoring Methodology
    Story.append(Paragraph("3. Predictive Scoring Methodology", h2_style))
    scoring_text = """
    Currently, the system employs a foundational rule-based heuristic model designed to simulate 
    the functionality of advanced deep-learning classifiers (e.g., DeepCRISPR, CRISPRon). The proprietary scoring algorithm calculates an "Efficiency Score" out of 100 based on the following physicochemical properties of the 20bp guide:
    <br/><br/>
    <b>A. GC Content Optimization:</b> The optimal GC content for an active biological guide resides between 40% and 60%. Guides falling within this thermodynamic window receive a positive modifier, whereas those outside this range incur penalties due to sub-optimal binding thermodynamics or unwinding difficulties.<br/>
    <b>B. Seed Region Constraints:</b> The 10-12 nucleotides closest to the PAM sequence constitute the 'seed region', which is hyper-sensitive to mismatches. The algorithm analyzes this region for penalizing motifs (e.g., poly-T tracts which can prematurely terminate RNA polymerase III transcription).<br/>
    <b>C. Positional Base Preferences:</b> Existing models consistently show that specific nucleotides at particular positions relative to the PAM strongly influence cleavage activity. The current heuristic applies weighted modifiers for favorable bindings (e.g., Guanine at position 20).
    """
    Story.append(Paragraph(scoring_text, body_style))
    
    # Section 4: Future integration
    Story.append(Paragraph("4. Ensemble AI Integration Roadmap", h2_style))
    future_text = """
    While the current architectural pipeline utilizes mathematical heuristics for immediate responsiveness and baseline validation, the microservice design inherently supports the integration of serialized ML models. 
    The next iteration of the API will load PyTorch/TensorFlow weights for Convolutional Neural Networks (CNNs) trained on empirical INDEL frequency datasets, allowing the application to serve as a unified ensemble classifier.
    """
    Story.append(Paragraph(future_text, body_style))
    
    # Section 5: Conclusion
    Story.append(Paragraph("5. Conclusion", h2_style))
    conclusion_text = """
    The AI-Powered gRNA Designer provides a comprehensive, responsive, and visually accessible platform for molecular biologists to rapid-prototype CRISPR experiments. The separation of concerns between the React frontend and the FastAPI backend ensures scalability, while the rigorous sequence parsing engine guarantees that only biologically plausible guides are suggested.
    """
    Story.append(Paragraph(conclusion_text, body_style))
    
    Spacer(1, 0.5 * inch)
    Story.append(Paragraph("References", h2_style))
    ref_text = """
    [1] Doench, J.G., et al. (2016). Optimized sgRNA design to maximize activity and minimize off-target effects of CRISPR-Cas9. Nature biotechnology, 34(2), 184-191.<br/>
    [2] Chuai, G., et al. (2018). DeepCRISPR: optimized CRISPR guide RNA design by deep learning. Genome biology, 19(1), 1-18.
    """
    Story.append(Paragraph(ref_text, body_style))

    doc.build(Story)
    print(f"Research PDF successfully generated at: {output_path}")

if __name__ == "__main__":
    generate_research_pdf("../gRNA_Designer_Methodology.pdf")
